import json
from . import db
from .models import User, Course, Module, Lesson, QuizQuestion, Scenario

# Content is intentionally separated by course, module and lesson. The material is
# written for an ND2-level cyber-safety learning platform and is based on current
# guidance from NIST, CISA, FTC consumer guidance and UNICEF online-safety guidance.
# Existing accounts and learning records are preserved when the content is reconciled.

COURSE_DATA = [
    {
        "title": "Cyber Safety Fundamentals",
        "description": "Build a practical foundation for recognising everyday digital risks, protecting information and responding safely to suspicious activity.",
        "modules": [
            ("Understanding Cyber Safety", [
                ("What Cyber Safety Means", "Cyber safety is the practice of reducing avoidable harm when using digital devices, services and networks. It includes protecting accounts and information, recognising suspicious behaviour, keeping software current and responding appropriately when something goes wrong.", "Cyber safety is not the same as being able to predict every attack. A safer habit is to pause before acting, check what a request is asking you to do, and use a trusted route to verify unexpected instructions. Good cyber safety also includes protecting other people's information and respecting access permissions.", "A student receives an unexpected message claiming that their school account will be closed unless they click a link. The student does not use the link. Instead, they open the normal school portal or contact the school through an independently known channel.", "Pause before acting; protect credentials; verify unexpected requests independently; report genuine incidents through the appropriate channel."),
                ("The Security Triad: Confidentiality, Integrity and Availability", "Confidentiality means information is only available to authorised people. Integrity means information remains accurate and is not changed improperly. Availability means authorised users can access information and services when needed.", "These three ideas are commonly called the CIA triad. A stolen student record is primarily a confidentiality problem; unauthorised changes to a grade are an integrity problem; and an unavailable learning portal is an availability problem. One incident can affect more than one property.", "If an attacker changes a student's payment details, the information may still be available, but its integrity has been damaged. If the attacker also publishes the details, confidentiality is affected too.", "Think about what must be kept secret, what must remain accurate, and what must remain accessible."),
                ("Threats, Vulnerabilities and Risk", "A threat is a potential source of harm, a vulnerability is a weakness that can be exploited, and risk describes the possibility and impact of harm when a threat can exploit a weakness.", "A suspicious message is not automatically a successful attack. Risk depends on the situation, including what is exposed, how likely misuse is, and what controls are available. Strong security combines people, processes and technology rather than relying on one tool.", "A phone with an outdated operating system may contain a vulnerability. A malicious application could exploit it. Updating the phone reduces the opportunity for that threat to succeed.", "Distinguish the threat from the weakness; consider likelihood and impact; reduce risk with practical controls."),
            ]),
            ("Recognising and Responding to Common Threats", [
                ("Malicious Links and Attachments", "Links and attachments can lead to credential theft, malicious downloads or deceptive websites. Treat unexpected files and links with caution, especially when a message creates pressure to act immediately.", "Do not rely only on appearance. Check the sender, context and destination using a safe method. If a message is unexpected, verify it independently before opening an attachment or entering credentials. Keep security software and the operating system updated.", "A supposed delivery notice contains an attachment you were not expecting. Instead of opening it, you check the delivery company's official app or website to see whether the notice exists.", "Unexpected does not mean safe; verify first; do not enter passwords after following an untrusted link."),
                ("Social Engineering Basics", "Social engineering uses human interaction and manipulation to influence someone into revealing information, transferring value or performing an unsafe action.", "Attackers may use urgency, fear, authority, familiarity, curiosity or a promise of reward. These cues are not proof that a message is fraudulent, but they are reasons to slow down and verify. A request from a familiar-looking account can still be unsafe if the account has been compromised.", "Someone claiming to be a supervisor asks an employee to buy gift cards urgently. The employee confirms the request through the supervisor's normal contact method rather than replying to the original message.", "Pressure is a reason to pause; verify through a separate trusted channel; never disclose passwords or one-time authentication codes to a requester."),
                ("What to Do When Something Goes Wrong", "A safe response to a suspected incident is to stop the risky action, preserve useful evidence where appropriate, secure affected accounts and report through a trusted process.", "The exact response depends on the incident. If credentials may have been exposed, change them through the legitimate service and enable stronger authentication where available. If malware is suspected, disconnecting a device from networks may help limit spread while you seek qualified support. Do not destroy evidence or investigate beyond your authority.", "After entering a password into a suspected fake site, a learner closes the page, signs in through the real service, changes the password, reviews account activity and reports the incident to the responsible organisation.", "Stop further exposure; secure the affected account or device; document what happened; report through a legitimate channel."),
            ]),
            ("Safer Everyday Digital Decisions", [
                ("Safe Browsing and Downloads", "Safer browsing involves using reputable sources, checking web addresses, avoiding unexpected downloads and keeping browsers and operating systems updated.", "A padlock or HTTPS indicates an encrypted connection but does not by itself prove that a website is legitimate. Look at the actual domain, the context of the request and whether you reached the site through a trusted route. Download software from reputable sources and review permissions before installation.", "A learner searches for a free application and finds several download sites. Instead of choosing the first result, the learner visits the developer's official site and checks the application's publisher and permissions.", "HTTPS protects the connection, not the identity of every website; use trusted sources; review downloads and permissions."),
                ("Public Devices and Shared Networks", "Shared computers and public networks can increase exposure because you may not control the device, network configuration or other users.", "Avoid sensitive activity on untrusted devices when possible. Do not save passwords in a shared browser, sign out after use and remove temporary files when appropriate. On public Wi-Fi, use secure websites and avoid assuming the network itself is trustworthy.", "A student needs to access a school account from a public computer. The student avoids saving credentials, uses the school's official website, signs out completely and checks that the session is closed.", "Do not trust shared devices by default; never save credentials on public computers; sign out and minimise sensitive activity."),
            ])
        ]
    },
    {
        "title": "Password and Account Security",
        "description": "Learn how passwords, passkeys, password managers and multi-factor authentication work together to reduce account takeover risk.",
        "modules": [
            ("Password Foundations", [
                ("Why Password Reuse Is Dangerous", "Using the same password on several services creates a chain of risk: if one service is breached or the password is exposed through phishing, attackers may try it on other services.", "NIST recommends moving away from weak and reused passwords and using a password manager where appropriate. The most important practical rule is to give important accounts unique credentials. Password length is also a major factor in resistance to guessing.", "A learner uses one password for email, school and social media. If the social account password is exposed, the attacker may try the same credential against the email account. Unique passwords break this chain.", "Use unique passwords; prioritise important accounts; use a password manager when practical."),
                ("Creating Stronger Passwords", "A strong password should be difficult for an attacker to guess and should not depend on obvious personal information.", "Length matters greatly. Avoid predictable choices such as names, birthdays, phone numbers or common phrases. Password managers can generate and store long unique passwords. Where a service supports passkeys, they can provide a phishing-resistant alternative to passwords.", "Instead of using a name and birth year, a learner lets a password manager generate a unique credential for a shopping account and stores it securely.", "Prefer length and uniqueness; avoid personal details; consider a password manager or passkey when supported."),
                ("Password Managers and Passkeys", "Password managers store credentials so users do not have to reuse or memorise many passwords. Passkeys use cryptographic credentials tied to a device or authenticator and are designed to resist common phishing of passwords.", "A password manager should itself be protected with strong authentication. Passkeys are different from passwords: the service stores a public key while the private key remains protected by the user's device or authenticator. Availability varies by service and device.", "A learner creates separate credentials for email, banking and social media with a password manager. For a service that supports passkeys, the learner registers a passkey instead of creating another password.", "Protect the password manager account; understand that passkeys and passwords work differently; use the strongest supported method."),
            ]),
            ("Multi-Factor and Account Protection", [
                ("How Multi-Factor Authentication Works", "Multi-factor authentication requires two or more different types of evidence, such as something you know, something you have or something you are.", "A password plus an authenticator-app code uses two factors. MFA can reduce the damage caused by a stolen password, although not every MFA method has the same resistance to phishing. Follow the service's security guidance and protect recovery methods too.", "A learner's password is exposed in a phishing incident, but the attacker cannot complete the login because the account also requires an authentication factor controlled by the learner.", "MFA adds a layer beyond the password; protect the second factor; prefer stronger phishing-resistant options when available."),
                ("Protecting Recovery and Login Notifications", "Account recovery can become an attack path if recovery email addresses, phone numbers or authentication methods are outdated or poorly protected.", "Keep recovery information current and review security notifications. Unexpected password-reset messages should be treated carefully. Do not approve an authentication request simply because it appears on your phone; confirm that you initiated the login.", "A learner receives a login approval prompt while not signing in. Instead of approving it, the learner denies the request and reviews the account's security activity.", "Protect recovery channels; reject unrequested authentication prompts; investigate unfamiliar security alerts through the real service."),
                ("Recognising Account Takeover", "Account takeover occurs when an unauthorised person gains control of an account. Signs can include unfamiliar logins, changed recovery information, unexpected messages, new devices or password-reset notices.", "If takeover is suspected, use the legitimate service to change the password, revoke unfamiliar sessions where supported, enable MFA and review recovery settings. Contact the service through its official support channel if access has been lost.", "Friends report receiving strange messages from a learner's social account. The learner checks active sessions, changes the password from the official app and removes unfamiliar sessions.", "Treat unfamiliar activity seriously; secure the account through official controls; warn contacts if malicious messages were sent."),
            ]),
            ("Authentication in Practice", [
                ("One-Time Codes, PINs and Secrets", "One-time passwords, PINs and recovery codes are authentication secrets. They should not be disclosed to another person simply because the requester claims to be support staff, a bank or an administrator.", "A legitimate service may send a code to confirm an action, but the user should enter it only into the service they intentionally opened. Unexpected requests for codes are a common social-engineering warning sign.", "Someone calls claiming to be from a bank and asks for the OTP that just arrived. The customer refuses and contacts the bank using the number on the official card or website.", "Treat authentication codes as secrets; never disclose them to callers or message senders; verify unusual requests independently."),
                ("Account Security Checklist", "Account security works best as a set of habits: unique credentials, MFA where available, secure recovery options, current software and careful response to unexpected login requests.", "Review the accounts that matter most, starting with email because it can be used to reset other services. Check active sessions and recovery methods periodically. Remove old accounts and unnecessary access where appropriate.", "A student secures the main email account first, enables MFA, reviews recovery settings and then applies similar protections to school and social accounts.", "Start with high-value accounts; layer controls; review account activity and recovery options regularly."),
            ])
        ]
    },
    {
        "title": "Phishing and Social Engineering",
        "description": "Learn how phishing, smishing, vishing, impersonation and manipulation work across email, SMS, websites, calls and social platforms.",
        "modules": [
            ("Phishing Channels", [
                ("Email Phishing", "Email phishing uses deceptive messages to persuade recipients to click, open, reply, pay or disclose information.", "Look beyond logos and display names. Examine the sender address, unexpected context, requests for credentials or money, attachments and links. Instead of using the message's contact details, reach the organisation through a known official route.", "An email says a student's account will be suspended today and includes a login button. The student opens the normal school portal instead of using the email button.", "Check context and sender details; avoid unexpected login links; verify using an independent channel."),
                ("Smishing and Messaging-App Phishing", "Smishing is phishing delivered by SMS or messaging services. Similar deception can appear in WhatsApp, Telegram or social direct messages.", "Short messages can create pressure because people read them quickly. Treat unexpected delivery, banking, job or account messages cautiously. Do not assume a familiar profile or phone number proves identity.", "A learner receives a WhatsApp message claiming to be a delivery agent asking for a small payment through an unfamiliar link. The learner checks the delivery using the company's official application.", "Messaging platforms can carry phishing too; verify outside the message; do not pay through an untrusted link."),
                ("Vishing and Impersonation Calls", "Vishing is voice-based phishing. The caller may impersonate a bank employee, technician, police officer, employer or relative to obtain information or money.", "Caller ID can be spoofed and familiar details can be copied. Do not treat a caller's knowledge of your name or partial information as proof of identity. End the call and contact the organisation using a trusted number when necessary.", "A caller claims to be technical support and asks the learner to read out a one-time code. The learner refuses and contacts the service through its official support page.", "Do not reveal authentication secrets by phone; end unexpected calls; call back through a trusted channel."),
                ("Fake Websites and Login Pages", "Phishing websites imitate legitimate services to capture credentials, payment details or other information.", "Inspect the domain and how you reached the page. A visually accurate logo does not prove legitimacy. HTTPS encrypts the connection but does not guarantee that the site is the real service.", "A learner receives a link to a page that looks like a cloud-storage login. Instead of signing in, the learner opens the provider's official site from a saved bookmark.", "Visual appearance is not proof; inspect the actual domain; use bookmarks or known addresses for sensitive services."),
            ]),
            ("Manipulation and Verification", [
                ("Urgency, Authority and Fear", "Social engineering often uses pressure such as urgency, authority, fear or a claim that an opportunity will disappear.", "These emotional triggers are useful warning signs because they encourage people to skip normal verification. A genuine urgent request may exist, but urgency should not remove the need for verification when sensitive information or money is involved.", "A message claims to come from a lecturer and asks for a payment within ten minutes. The student checks with the lecturer through the institution's normal contact method.", "Pressure is not proof; slow down; verify high-impact requests through a separate trusted route."),
                ("Impersonation and Context Manipulation", "Attackers may copy names, logos, writing styles or public information to appear familiar. They may also use information from social media to make a request sound credible.", "Identity should be verified using more than appearance. For important requests, confirm the person and the request through a channel that was not supplied by the suspicious message.", "An attacker creates an account using a manager's name and photo and asks an employee to transfer funds. The employee calls the manager through the normal office contact.", "Familiar names and photos can be copied; verify identity and intent separately."),
                ("Independent Verification", "Independent verification means checking a request using a trusted route that is not controlled by the person who sent the suspicious request.", "For example, type the official website yourself, use a saved contact, call a known number or speak directly with the person. Do not simply reply to the suspicious message and ask whether it is genuine.", "A learner receives a password-reset email. Rather than clicking its button, the learner opens the service directly and checks the account's security page.", "Use a separate trusted route; verify both the identity and the requested action; do not rely on the suspicious channel."),
            ]),
            ("Phishing Response", [
                ("What to Do After Clicking a Suspicious Link", "Clicking a suspicious link does not automatically mean an account or device is compromised, but it should trigger a careful response.", "If credentials were entered, change the affected password through the legitimate service and review account activity. If a file was downloaded or malware is suspected, stop interacting with it and seek appropriate technical support. Report the message through the relevant service.", "A learner clicked a fake login page but did not submit credentials. The learner closes it, reports the message and checks that no unexpected download occurred.", "Do not panic; determine what information or action occurred; secure affected accounts or devices; report the incident."),
                ("Reporting Phishing", "Reporting suspicious messages can help organisations remove malicious content and protect other users.", "Use the reporting feature of the email or messaging service and follow the organisation's official reporting process. In an academic or workplace setting, preserve relevant details without spreading the malicious link to others.", "A student receives a fake school announcement. The student reports it to the institution's IT/security contact and marks the message as phishing instead of forwarding it to classmates.", "Report through legitimate channels; avoid spreading malicious content; preserve useful evidence when appropriate."),
                ("Phishing Knowledge Check in Real Life", "Recognising phishing is a reasoning task: identify the request, inspect the context, look for manipulation and verify before acting.", "No single clue proves that a message is malicious. Strong decisions combine multiple signals and the consequences of the requested action. When the cost of verification is low and the impact of a mistake is high, verification is especially important.", "A message asks for a password, uses urgent language and provides an unfamiliar link. Several warning signs appear, so the learner verifies the request independently rather than responding.", "Combine clues; consider consequences; verify before high-impact actions."),
            ])
        ]
    },
    {
        "title": "Online Scams and Fraud Awareness",
        "description": "Recognise common online fraud patterns involving jobs, scholarships, giveaways, investments, payments and impersonation before acting.",
        "modules": [
            ("Common Scam Patterns", [
                ("Fake Job and Recruitment Scams", "Fake job scams may use real company names, social media posts or unsolicited messages to request money or sensitive information from job seekers.", "Consumer guidance warns about offers that require applicants to pay for a job, training, starter kit or certification, as well as fake-check arrangements that ask the recipient to send money onward. Verify the employer using independently sourced contact details.", "A student receives a remote job offer by WhatsApp and is told to pay a registration fee before the interview. The student checks the company's official careers page and does not pay.", "Never pay to obtain a job; verify employers independently; be cautious with unexpected recruiter messages and checks."),
                ("Scholarship, Grant and Giveaway Scams", "Fraudulent scholarship and giveaway offers often promise benefits that require an upfront fee or personal and financial information.", "Be cautious when an offer claims you were selected for something you never entered or demands a processing or redemption fee. Check the programme through the official institution or organiser rather than the contact details in the offer.", "A learner receives a message saying they won a scholarship but must pay a processing fee immediately. The learner searches for the scholarship on the institution's official website and finds no such programme.", "Unexpected prizes and scholarships require verification; do not pay upfront fees simply to receive a promised benefit."),
                ("Prize and Giveaway Impersonation", "Prize scams use the excitement of a supposed reward to pressure people into paying fees, sharing information or clicking links.", "A legitimate competition normally has identifiable rules and an organiser. Be cautious if you are told to pay taxes, delivery charges or activation fees through unusual payment methods before receiving a prize. Verify the promotion independently.", "A social-media account claims that a learner won a phone and asks for a delivery payment through a private wallet. The learner checks the organiser's verified page and official competition rules.", "Verify the organiser and rules; unexpected winnings deserve scrutiny; do not rush because a reward is time-limited."),
            ]),
            ("Money and Payment Scams", [
                ("Investment and Get-Rich-Quick Scams", "Investment scams commonly promise high or easy returns with little or no risk and may use testimonials, social media or free seminars to build trust.", "A promise of guaranteed profit is not evidence of a legitimate investment. Research the organisation independently, understand the risk, and do not transfer funds simply because someone creates urgency or shows supposed earnings.", "An online group claims members can double their money in days with no risk. A learner does not deposit money and instead checks the investment provider through independent sources and appropriate regulators.", "High returns with little risk are a warning sign; verify the provider; understand the investment before committing money."),
                ("Payment Redirection and Fake Invoices", "Fraud can involve requests to send money to a new account, pay a fake invoice or change payment details unexpectedly.", "For businesses and institutions, payment changes should be verified using established procedures. For individuals, independently confirm the recipient and amount before transferring funds, especially when account details have changed.", "A supplier emails new bank details for an outstanding invoice. The finance worker confirms the change using the supplier's existing phone number rather than replying to the email.", "Verify payment changes out of band; do not rely solely on an email; check recipient details before sending money."),
                ("Task and Advance-Fee Scams", "Some online task scams show fake earnings and later require the victim to deposit personal funds to unlock tasks or withdraw supposed profits.", "Unexpected offers to earn money by liking, rating or completing simple online tasks can be used to build trust before demanding a deposit. The appearance of earnings in an app does not prove that the money is real.", "A learner receives a Telegram offer to earn commissions by rating products. After small tasks, the platform asks for a deposit to unlock a higher level. The learner stops instead of paying.", "Do not pay to unlock supposed earnings; treat unexpected task offers cautiously; do not mistake displayed balances for real funds."),
            ]),
            ("Verification Before Action", [
                ("A Practical Scam Verification Process", "A simple verification process can reduce impulsive decisions: stop, identify the claim, check the source independently, verify the payment or data request, then decide.", "Search for the organisation using a known official website rather than a link supplied by the message. Check whether the offer exists and whether the contact details match. When money or identity information is involved, ask for a second source of confirmation.", "A supposed training programme asks for a deposit to reserve a place. The learner finds the institution's official website, checks its admissions information and contacts the published office before paying.", "Pause; verify the organisation; verify the exact offer; confirm payment details; keep records."),
                ("Protecting Financial and Identity Information", "Bank details, payment credentials, identity documents, authentication codes and other personal information can be valuable to fraudsters.", "Only provide sensitive information when there is a clear legitimate need and you have verified who is collecting it. Do not send PINs, passwords or one-time codes to people who ask through calls or messages.", "A supposed recruiter asks for a bank login and OTP to 'set up salary payments'. The applicant refuses and contacts the employer through its official recruitment channel.", "Minimise data sharing; protect authentication secrets; verify why sensitive information is needed before providing it."),
                ("After a Scam or Suspected Fraud", "If money or information has already been exposed, quick and organised action can reduce further harm.", "Contact the affected bank or service using official channels, secure compromised accounts, preserve transaction or message records and report the incident to the appropriate organisation or authority. Avoid sending additional money to someone promising to recover funds for a fee.", "After a fraudulent transfer, a learner contacts the bank through its official support channel, records the transaction details, changes exposed credentials and reports the incident.", "Act quickly through legitimate channels; preserve evidence; secure accounts; be cautious of follow-up recovery scams."),
            ])
        ]
    },
    {
        "title": "Social Media Safety and Digital Privacy",
        "description": "Develop safer habits for sharing, privacy settings, digital footprints, online communication and social-platform security.",
        "modules": [
            ("Sharing and Visibility", [
                ("Digital Footprints", "A digital footprint is the trail of information created by online activity, including posts, comments, uploads, profiles and interactions.", "Information can be copied, reshared or archived even after a user deletes the original. Before posting, consider the audience, future consequences and whether the information exposes you or another person unnecessarily.", "A student plans to post a photo showing a school ID card. Before posting, the student notices the ID number and covers it because the information is not necessary for the post.", "Think before posting; consider persistence and audience; avoid exposing unnecessary personal information."),
                ("Oversharing and Location Information", "Oversharing can reveal details such as routines, locations, school or workplace, travel plans or contact information that others could misuse.", "Location tags and real-time updates can reveal where someone is. Privacy is not achieved by hiding one item while publicly exposing many others. Share only what is needed with the intended audience.", "A learner wants to announce a trip while away from home. Instead of posting the exact location in real time, the learner waits until returning and shares a general experience.", "Avoid real-time location exposure; review what a post reveals indirectly; share with an appropriate audience."),
                ("Audience and Content Controls", "Social platforms provide controls for who can view posts, contact an account or access profile information, but settings vary and can change.", "Review privacy settings after major platform changes. Separate public content from information intended for a limited audience. Remember that even private content can be copied by recipients.", "A student reviews a social account and changes an old post containing a phone number from public visibility to a more restricted setting, then removes the number entirely.", "Use privacy controls; review old content; remember that recipients can still copy or reshare content."),
            ]),
            ("Privacy Controls", [
                ("App Permissions", "Apps may request access to contacts, camera, microphone, location, photos and other device features. Permission should match the app's purpose.", "Review permissions and remove access that is unnecessary. A navigation app may need location while a simple note-taking app may not need contacts. Permission decisions should consider both function and trust.", "A photo-editing app asks for continuous location access even though the feature does not require it. The user denies the unnecessary permission and checks whether the app still works.", "Grant only necessary permissions; review permissions periodically; understand what data access an app receives."),
                ("Account Privacy and Security Settings", "Privacy settings control visibility and communication, while security settings help protect account access. Both matter.", "Review who can find, message or tag the account, and examine login alerts and multi-factor authentication. Privacy controls do not replace account security controls.", "A learner limits who can send message requests, enables MFA and reviews active sessions after noticing an unfamiliar login notification.", "Privacy and security settings solve different problems; configure both; review them after major changes."),
                ("Third-Party Apps and Connected Accounts", "Third-party applications can receive access to an account or data when a user grants permission. Old connections can remain unnecessary after an app is no longer used.", "Review connected applications and revoke access that is no longer needed. Use official account settings rather than links sent by unknown messages when managing permissions.", "A student discovers an old quiz app still has access to a social account. The student removes the connection through the platform's official settings.", "Audit connected apps; remove unused access; avoid granting permissions simply to unlock a feature."),
            ]),
            ("Responsible Participation", [
                ("Cyberbullying and Harmful Online Behaviour", "Cyberbullying can involve repeated harmful messages, humiliation, threats or exclusion through digital platforms. Online harm can have real effects on a person's wellbeing and participation.", "Do not join, amplify or redistribute harmful content. Save relevant evidence when appropriate, use platform reporting tools and seek help from a trusted adult, school or responsible authority when safety is at risk.", "A group chat begins sharing humiliating images of a classmate. A student does not forward the images, reports the content and tells a responsible school adult.", "Do not amplify harm; report abusive content; seek support when threats or serious harm are involved."),
                ("Misinformation, Manipulation and Critical Thinking", "Not every false online claim is created with the same intent. Users should evaluate sources, evidence, dates and context before sharing information.", "Check whether the claim is supported by credible sources. Be cautious with screenshots without context, sensational headlines and posts that discourage verification. For important claims, consult primary or authoritative sources.", "A viral post claims that a new school policy starts tomorrow. Before forwarding it, a student checks the institution's official notice and finds that the viral post is outdated.", "Check the source and date; seek corroboration; avoid forwarding claims simply because they are emotional or popular."),
            ])
        ]
    },
    {
        "title": "Device, Malware and Internet Safety",
        "description": "Understand malware, safer downloads, software updates, device protection, permissions, browsers and network risks.",
        "modules": [
            ("Malware Basics", [
                ("What Malware Is", "Malware is malicious software designed to disrupt, damage, spy on, steal from or gain unauthorised access to systems or data.", "Malware is a broad category that includes viruses, worms, trojans, ransomware and spyware. Different malware behaves differently, so users should not assume that one symptom proves a specific infection.", "A user installs an unofficial application that secretly collects information. The behaviour is malicious even though the application looks normal on the surface.", "Malware is an umbrella term; avoid untrusted software; investigate suspicious behaviour carefully."),
                ("Ransomware, Spyware and Trojans", "Ransomware can deny access to data, spyware can monitor or collect information, and trojans disguise malicious functionality as legitimate software.", "The exact behaviour varies by malware family. Good prevention includes current software, safe downloads, least-privilege use and reliable backups. No single control guarantees protection.", "A user downloads a cracked application that contains a trojan. After installation, unexpected processes appear and files become inaccessible. The user disconnects the device and seeks technical assistance.", "Avoid pirated or untrusted software; keep backups; respond quickly to suspected compromise."),
                ("How Malware Gets In", "Malware can arrive through malicious attachments, deceptive downloads, compromised websites, removable media, vulnerable software or other delivery methods.", "Users should consider both the source and the action. Opening an unexpected file, installing software from an unknown publisher or disabling security controls can increase exposure.", "An email attachment claims to be an invoice but the recipient was not expecting it. The recipient verifies the invoice through the supplier's known contact before opening anything.", "Unexpected files deserve verification; use trusted software sources; keep security controls enabled."),
            ]),
            ("Safer Devices", [
                ("Software Updates and Security Patches", "Updates often include security fixes that address known vulnerabilities. Delaying important updates can leave a device exposed to weaknesses that attackers already know about.", "Enable automatic updates where appropriate and restart devices when required. Update the operating system, browser, applications and security tools. Unsupported software may no longer receive fixes and should be replaced when practical.", "A laptop repeatedly postpones operating-system updates. The owner changes the settings so security updates install automatically and restarts when prompted.", "Keep supported software current; install security updates promptly; do not ignore repeated update warnings."),
                ("Device Locking and Physical Security", "Physical access can expose data even when online accounts are well protected. Screen locks, device encryption and careful handling reduce this risk.", "Use a strong device PIN or password and enable automatic locking. Do not leave an unlocked phone or laptop unattended in public. If a device is lost, use available account or device-management tools to protect it.", "A student leaves a laptop in a library for a few minutes. Instead of leaving it unlocked, the student locks the screen before stepping away.", "Protect the device physically; lock screens; use available encryption and remote-protection features."),
                ("Backups and Recovery", "Backups provide a way to recover important data after accidental deletion, device failure or some malware incidents.", "Important backups should not all be continuously exposed to the same device or account. Test that backups can actually be restored. Back up irreplaceable school and personal work according to its importance.", "A learner keeps coursework in the only copy on a laptop. After the drive fails, the work is lost. A better approach is to maintain a separate, reliable backup and test it periodically.", "Back up important data; keep recovery options separate; test restoration rather than assuming a backup works."),
            ]),
            ("Browsing and Networks", [
                ("Browser Safety and Downloads", "Browsers are a major gateway to online content. Safer use includes keeping the browser current, limiting risky extensions and downloading software from trusted sources.", "Be cautious with pop-ups that claim the device is infected or urgently needs a download. Do not install browser extensions simply because a webpage says they are required. Review extension permissions and remove unused extensions.", "A webpage displays a fake security alert telling the user to install a 'cleaner'. The user closes the page and uses the device's normal security tools instead.", "Do not trust browser pop-ups as security authorities; use reputable software sources; review extensions."),
                ("Public Wi-Fi and Network Safety", "Public Wi-Fi can be useful but users should not assume that every network is trustworthy or that joining it makes all activity safe.", "Use secure websites and applications, avoid unnecessary sensitive transactions on untrusted networks and keep devices updated. Be alert to fake network names and unexpected login pages.", "A learner connects to public Wi-Fi and receives a pop-up asking for an email password. The learner closes it and avoids entering credentials into an unfamiliar portal.", "Treat public networks cautiously; use encrypted services; do not enter credentials into unexpected network pages."),
                ("Safe Application Permissions", "Applications should receive only the device access they need for legitimate functions. Excessive permissions can increase privacy and security exposure.", "Before installing an app, consider its publisher, reputation, purpose and requested permissions. Review permissions after updates because an app's functionality can change.", "A calculator app requests access to contacts, microphone and precise location. The user questions the need for those permissions and chooses a more appropriate application.", "Check the publisher and purpose; question excessive permissions; review access periodically."),
            ])
        ]
    },
    {
        "title": "Data Privacy and Digital Citizenship",
        "description": "Understand personal data, responsible collection and sharing, privacy choices, consent, digital identity and respectful participation online.",
        "modules": [
            ("Personal Data", [
                ("What Counts as Personal Data", "Personal data is information that relates to an identifiable person. Examples can include names, contact details, identifiers, location information and account information.", "Different contexts define categories differently, and some data can become identifying when combined with other information. Treat information about other people with the same care you expect for your own.", "A class spreadsheet contains names, phone numbers and student IDs. Even though each field seems ordinary, together they identify individuals and should not be posted publicly.", "Consider whether information can identify a person; minimise unnecessary exposure; protect other people's data too."),
                ("Sensitive Information and Identity Theft", "Some information can create greater harm if exposed, including authentication secrets, financial information and certain identity records.", "The sensitivity of data depends on context. Passwords, PINs and one-time codes should be treated as authentication secrets. Identity documents and financial information should be shared only when necessary with a verified recipient.", "A learner is asked to send a photo of an identity document to an unknown recruiter. The learner verifies the organisation and asks why the document is required before providing anything.", "Classify information by sensitivity; verify recipients; never share authentication secrets casually."),
                ("Data Minimisation", "Data minimisation means collecting, sharing or retaining only what is necessary for a legitimate purpose.", "Before providing information, ask what is needed, why it is needed, who will receive it and how it will be protected. Avoid providing extra information simply because a form asks for it when it is not necessary or required.", "A club registration form asks for a member's full address even though only an email is needed for event notices. The organiser reviews whether the address is genuinely necessary.", "Ask why data is needed; provide the minimum appropriate information; avoid unnecessary collection."),
            ]),
            ("Privacy Choices and Data Handling", [
                ("Privacy Settings and Permissions", "Privacy settings help control visibility and access, while application permissions determine what device resources an app can use.", "Review settings on social networks, browsers and mobile devices. Limit location, contacts, microphone, camera and photo access when the function does not require them. Settings are not permanent, so revisit them after updates.", "A messaging app has access to contacts because it needs them to find friends, but a simple game does not. The user denies the game's unnecessary contact access.", "Use privacy controls deliberately; grant permissions based on need; review changes over time."),
                ("Data Collection and Third Parties", "Online services may collect information for functions such as account management, analytics, personalisation or advertising. Data may also be processed by third parties depending on the service.", "Read privacy information when the decision matters, especially before providing sensitive information. Understand that privacy is not simply a security issue: data can create privacy risks even when no attacker is involved.", "A user installs an app that requests extensive profile information. Before accepting, the user checks what the app collects and whether the requested information is necessary for its stated purpose.", "Privacy risk can arise from normal data processing; understand collection and sharing; minimise unnecessary data."),
                ("Data Retention, Deletion and Digital Traces", "Deleting information from one service does not guarantee that every copy or record disappears. Backups, recipients and other systems may retain information according to their own practices.", "Think about retention before sharing. For accounts you no longer use, remove unnecessary data and close the account where appropriate. Do not assume that deletion means an immediate universal erasure.", "A learner deletes an old social post but realises that another person may have saved a copy. The learner therefore treats future posts as potentially persistent.", "Assume online information can persist; delete unnecessary data where possible; make careful decisions before sharing."),
            ]),
            ("Digital Citizenship", [
                ("Respect, Consent and Intellectual Property", "Digital citizenship involves responsible participation, including respecting privacy, consent, ownership and the rights of other users.", "Do not post another person's photo or private message simply because you can access it. Credit creators where appropriate and respect platform rules and applicable laws. Permission to view information is not automatically permission to redistribute it.", "A student receives a private voice note from a friend and wants to post it publicly. The student asks for permission first and accepts the friend's decision.", "Access is not consent to redistribute; respect privacy; credit and follow legitimate use rules."),
                ("Responsible Communication and Permanent Records", "Online communication can be copied, forwarded and misunderstood without tone or context. Responsible communication reduces avoidable harm.", "Pause before posting when angry. Avoid threats, harassment and humiliating content. Remember that screenshots and forwarded messages can preserve statements after deletion.", "During an argument, a student writes an insulting message but waits before sending it. After reconsidering the consequences, the student communicates the disagreement respectfully.", "Pause before posting; communicate respectfully; assume important messages may be preserved."),
            ])
        ]
    },
]


def _slug(title):
    return title.lower().replace(' ', '-').replace('&', 'and').replace('/', '-')


def _lesson_question(title, content, correct, distractors, explanation):
    options=[correct]+distractors
    return QuizQuestion(question=f"Which statement is most consistent with the guidance in '{title}'?", options=json.dumps(options), correct_index=0, explanation=explanation)


def _lesson_scenario(title, prompt, correct, alternatives, explanation):
    choices=[correct]+alternatives
    return Scenario(prompt=prompt, choices=json.dumps(choices), correct_index=0, explanation=explanation)


def _reconcile_course(course_data):
    course=Course.query.filter_by(title=course_data['title']).first()
    if not course:
        course=Course(title=course_data['title'], slug=_slug(course_data['title']), description=course_data['description'])
        db.session.add(course); db.session.flush()
    else:
        course.description=course_data['description']; course.slug=_slug(course_data['title'])
    for mi,(module_title, lessons) in enumerate(course_data['modules'],1):
        module=Module.query.filter_by(course_id=course.id,position=mi).first()
        if not module:
            module=Module(course_id=course.id,position=mi,title=module_title); db.session.add(module); db.session.flush()
        else: module.title=module_title
        for li,data in enumerate(lessons,1):
            title,content,detail,example,takeaways=data
            lesson=Lesson.query.filter_by(module_id=module.id,position=li).first()
            if not lesson:
                lesson=Lesson(module_id=module.id,position=li,title=title,objectives='',content='',examples='',takeaways=''); db.session.add(lesson); db.session.flush()
            lesson.title=title
            lesson.objectives="By the end of this lesson, the learner should be able to explain the main idea, recognise its practical warning signs and choose an appropriate safer response."
            lesson.content=content+"\n\n"+detail; lesson.examples=example; lesson.takeaways=takeaways
            correct=takeaways
            distractors=["Ignore the lesson guidance and act immediately when the situation feels urgent.","Share sensitive information first and verify the situation afterwards.","Assume the situation is safe because it looks familiar or professional."]
            q=lesson.questions[0] if lesson.questions else None
            if not q: q=_lesson_question(title,content,correct,distractors,f"The lesson on {title} specifically teaches: {takeaways}"); q.lesson_id=lesson.id; db.session.add(q)
            else:
                q.question=f"Which statement is most consistent with the guidance in '{title}'?"; q.options=json.dumps([correct]+distractors); q.correct_index=0; q.explanation=f"The lesson on {title} specifically teaches: {takeaways}"
            sc=Scenario.query.filter_by(lesson_id=lesson.id).first()
            alternatives=["Act immediately without checking whether the situation is legitimate or safe.","Provide sensitive information first and investigate only if something goes wrong.","Treat the situation as trustworthy simply because the message, person or service looks familiar."]
            if not sc: sc=_lesson_scenario(title,example,takeaways,alternatives,f"A safer response for {title} follows the lesson guidance: {takeaways}"); sc.lesson_id=lesson.id; db.session.add(sc)
            else:
                sc.prompt=example; sc.choices=json.dumps([takeaways]+alternatives); sc.correct_index=0; sc.explanation=f"A safer response for {title} follows the lesson guidance: {takeaways}"
    return course


def seed_database():
    for data in COURSE_DATA: _reconcile_course(data)
    db.session.commit()
